language: python

addons:
  apt:
    packages:
      - poppler-utils

install:
  - pip install tox codecov

matrix:
  include:
    - python: 3.5
      env: ENV=py35-1.10
    - python: 3.6
      env: ENV=py36-1.11
    - python: 3.5
      env: ENV=py35-1.10
    - python: 3.6
      env: ENV=py36-1.11
    - python: 3.5
      env: ENV=py35-1.10
    - python: 3.6
      env: ENV=py36-1.11
    - python: 3.4
      env: ENV=flake8
    - python: 3.5
      env: ENV=coverage

script: tox -e $ENV

after_success:
  - codecov
