# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20170212_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='qty_multiplier',
            field=models.PositiveIntegerField(default=1, help_text='The quantity in the report will be multiplied by this value.', verbose_name='Quantity multiplier'),
        ),
    ]
