# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_auto_20170218_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='trx_status',
        ),
    ]
